## Tensorflow 시작하기
* 자료형 선언
* 텐서플로워 연산
* 텐서플로워 그래프 생성 및 실행

## 01. 라이브러리 임포트

In [1]:
import tensorflow as tf

/Users/toto/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


## 02. 값을 저장하기
 * Tensor라는 자료형
 * shape()
 * dtype(자료형) : 문자열

In [2]:
hello = tf.constant("Hello, Tensorflow")
print(hello)

Tensor("Const:0", shape=(), dtype=string)


## 03. 텐서플로워 연산
 * 그래프의 생성과 그래프의 실행

### 3-1 그래프의 생성
 * 그래프는 간단하게 말하면 텐서들의 연산 모음.
 * 텐서와 텐서의 연산들을 먼저 정의하여 그래프를 만든다.

In [3]:
a = tf.constant(10)
b = tf.constant(25)
c = tf.add(a,b)
print(c )
print(type(c))

Tensor("Add:0", shape=(), dtype=int32)
<class 'tensorflow.python.framework.ops.Tensor'>


### 3-2 그래프의 실행
 * 실제 연산 부분 C++로 구현한 코어 라이브러리에서 수행
 * 모델 구성과 실행을 분리하여 프로그램을 깔끔하게 작성

In [4]:
sess = tf.Session()
print(sess.run(hello))
print(sess.run([a,b,c]))

sess.close()

b'Hello, Tensorflow'
[10, 25, 35]


### 3-3 플레이스홀더와 변수
 * 플레이스 홀더(Placeholder) : 나중에 값을 입력받기 위한 사용되는 매개변수(parameter)
 * shape(?,3)은 두번째 차원 요소가 3임을 의미한다.

### 플레이스 홀더 선언

In [5]:
# None은 크기가 정해져 있지 않음을 의미
X = tf.placeholder(tf.float32, [None, 3])
print(X)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


### 추후에 넣을 데이터 x

In [9]:
x_data = [[1,2,3], [4,5,6]]
print(x_data)

[[1, 2, 3], [4, 5, 6]]


### 변수 정의
 * tf.random_normal 함수를 이용한 정규 분포의 무작위 행렬 3,2 생성

In [13]:
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([2,1]))
print(W)
print(b)

<tf.Variable 'Variable_2:0' shape=(3, 2) dtype=float32_ref>
<tf.Variable 'Variable_3:0' shape=(2, 1) dtype=float32_ref>


### 수식 계산


In [14]:
# X = tf.placeholder(tf.float32, [None, 3])   # [? * 3] X [3 * 2] => ? X 2 
# W = tf.Variable(tf.random_normal([3,2]))

expr = tf.matmul(X, W) + b
expr

<tf.Tensor 'add_3:0' shape=(2, 2) dtype=float32>

### 연산 실행 및 결과 출력

In [17]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print("=== x_data ===")
print(x_data)
print("=== W matrix ===")
print(sess.run(W))
print("=== b ===")
print(sess.run(b)) 
print("=== expr ===")
print(sess.run(expr, feed_dict={X:x_data}))

sess.close()

=== x_data ===
[[1, 2, 3], [4, 5, 6]]
=== W matrix ===
[[ 1.4617208   0.25130886]
 [-0.89442915  0.63962835]
 [ 1.4320164   0.72631794]]
=== b ===
[[-0.29359195]
 [-0.0188987 ]]
=== expr ===
[[3.6753197 3.4159274]
 [9.947937  8.542386 ]]
